import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'pt', 'es', 'it', 'de', 'zh_Hans', 'zh_Hant', 'ru', 'ja', 'ko'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? ptText = '',
    String? esText = '',
    String? itText = '',
    String? deText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? ruText = '',
    String? jaText = '',
    String? koText = '',
  }) =>
      [
        enText,
        ptText,
        esText,
        itText,
        deText,
        zh_HansText,
        zh_HantText,
        ruText,
        jaText,
        koText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // TourismsPage
  {
    '0tr1tc9v': {
      'en': 'Search tourist points...',
      'de': 'Touristische Punkte suchen...',
      'es': 'Buscar puntos turísticos...',
      'it': 'Cerca punti turistici...',
      'ja': '観光ポイントを検索...',
      'ko': '관광지 검색...',
      'pt': 'Pesquisar pontos turísticos...',
      'ru': 'Поиск туристических точек...',
      'zh_Hans': '搜索旅游点...',
      'zh_Hant': '搜索旅遊點...',
    },
    'gicrqril': {
      'en': 'Tourist Points',
      'de': 'Touristenpunkte',
      'es': 'Puntos Turísticos',
      'it': 'Punti turistici',
      'ja': '観光ポイント',
      'ko': '관광포인트',
      'pt': 'Pontos Turísticos',
      'ru': 'Туристические точки',
      'zh_Hans': '旅游点',
      'zh_Hant': '旅遊點',
    },
  },
  // AuthPage
  {
    'wmm1js2a': {
      'en': 'Sign In',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'it': 'Registrazione',
      'ja': 'サインイン',
      'ko': '로그인',
      'pt': 'Entrar',
      'ru': 'Войти',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    '320mgrwf': {
      'en': 'Email Address',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'zh_Hans': '电子邮件地址',
      'zh_Hant': '電子郵件地址',
    },
    'jdrn7y5r': {
      'en': 'Enter your email...',
      'de': 'Geben sie ihre E-Mail Adresse ein...',
      'es': 'Introduce tu correo electrónico...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ja': 'メールアドレスを入力...',
      'ko': '이메일을 입력하세요...',
      'pt': 'Digite seu e-mail...',
      'ru': 'Введите адрес электронной почты...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵箱...',
    },
    '0rzuy9rl': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'pt': 'Senha',
      'ru': 'Пароль',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'h3mmrgp9': {
      'en': 'Enter your password...',
      'de': 'Geben Sie Ihr Passwort ein...',
      'es': 'Ingresa tu contraseña...',
      'it': 'Inserisci la tua password...',
      'ja': 'パスワードを入力してください...',
      'ko': '비밀번호를 입력하세요...',
      'pt': 'Coloque sua senha...',
      'ru': 'Введите ваш пароль...',
      'zh_Hans': '输入您的密码...',
      'zh_Hant': '輸入您的密碼...',
    },
    'm3sx80ro': {
      'en': 'Sign In',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'it': 'Registrazione',
      'ja': 'サインイン',
      'ko': '로그인',
      'pt': 'Entrar',
      'ru': 'Войти',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    '2t4avplr': {
      'en': 'Forgot Password?',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'it': 'Ha dimenticato la password?',
      'ja': 'パスワードをお忘れですか？',
      'ko': '비밀번호를 잊으 셨나요?',
      'pt': 'Esqueceu sua senha?',
      'ru': 'Забыли пароль?',
      'zh_Hans': '忘记密码？',
      'zh_Hant': '忘記密碼？',
    },
    'akh4dv0l': {
      'en': 'Or use a social account to login',
      'de': 'Oder verwenden Sie ein soziales Konto, um sich anzumelden',
      'es': 'O use una cuenta social para iniciar sesión',
      'it': 'Oppure utilizza un account social per accedere',
      'ja': 'またはソーシャルアカウントを使用してログインしてください',
      'ko': '또는 소셜 계정을 사용하여 로그인하세요.',
      'pt': 'Ou use uma conta social para fazer login',
      'ru': 'Или используйте учетную запись социальной сети для входа',
      'zh_Hans': '或使用社交账号登录',
      'zh_Hant': '或使用社交賬號登錄',
    },
    'wmh90oaq': {
      'en': 'Sign Up',
      'de': 'Melden Sie sich an',
      'es': 'Inscribirse',
      'it': 'Iscrizione',
      'ja': 'サインアップ',
      'ko': '가입하기',
      'pt': 'Inscrever-se',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '报名',
      'zh_Hant': '報名',
    },
    's34fmkz8': {
      'en': 'Email Address',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'zh_Hans': '电子邮件地址',
      'zh_Hant': '電子郵件地址',
    },
    'cmc7lupt': {
      'en': 'Enter your email...',
      'de': 'Geben sie ihre E-Mail Adresse ein...',
      'es': 'Introduce tu correo electrónico...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ja': 'メールアドレスを入力...',
      'ko': '이메일을 입력하세요...',
      'pt': 'Digite seu e-mail...',
      'ru': 'Введите адрес электронной почты...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵箱...',
    },
    'pql4dbwn': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'pt': 'Senha',
      'ru': 'Пароль',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    '42pyp3xa': {
      'en': 'Enter your password...',
      'de': 'Geben Sie Ihr Passwort ein...',
      'es': 'Ingresa tu contraseña...',
      'it': 'Inserisci la tua password...',
      'ja': 'パスワードを入力してください...',
      'ko': '비밀번호를 입력하세요...',
      'pt': 'Coloque sua senha...',
      'ru': 'Введите ваш пароль...',
      'zh_Hans': '输入您的密码...',
      'zh_Hant': '輸入您的密碼...',
    },
    'f1abiaa0': {
      'en': 'Confirm Password',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'it': 'Conferma password',
      'ja': 'パスワードを認証する',
      'ko': '비밀번호 확인',
      'pt': 'Confirme sua senha',
      'ru': 'Подтвердите пароль',
      'zh_Hans': '确认密码',
      'zh_Hant': '確認密碼',
    },
    '60zputvu': {
      'en': 'Confirm your password...',
      'de': 'Bestätigen Sie Ihr Passwort...',
      'es': 'Confirmar la contraseña...',
      'it': 'Conferma la tua password...',
      'ja': 'あなたのパスワードを確認...',
      'ko': '암호를 확인...',
      'pt': 'Confirme sua senha...',
      'ru': 'Подтвердите ваш пароль...',
      'zh_Hans': '确认你的密码...',
      'zh_Hant': '確認你的密碼...',
    },
    'qzrvt30z': {
      'en': 'Create Account',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ko': '계정 만들기',
      'pt': 'Criar uma conta',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '创建账户',
      'zh_Hant': '創建賬戶',
    },
    '4vjon5z7': {
      'en': 'Sign up using a social account',
      'de': 'Melden Sie sich mit einem sozialen Konto an',
      'es': 'Regístrese usando una cuenta social',
      'it': 'Iscriviti utilizzando un account social',
      'ja': 'ソーシャルアカウントを使用してサインアップする',
      'ko': '소셜 계정을 사용하여 가입',
      'pt': 'Inscreva-se usando uma conta social',
      'ru': 'Зарегистрируйтесь с помощью социальной учетной записи',
      'zh_Hans': '使用社交帐户注册',
      'zh_Hant': '使用社交帳戶註冊',
    },
    's5r88r9j': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // ProfilePage
  {
    'qawb6l2w': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'it': 'Impostazioni',
      'ja': '設定',
      'ko': '설정',
      'pt': 'Configurações',
      'ru': 'Настройки',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
    'ehnyf6k8': {
      'en': 'Phone Number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'it': 'Numero di telefono',
      'ja': '電話番号',
      'ko': '전화 번호',
      'pt': 'Número de telefone',
      'ru': 'Номер телефона',
      'zh_Hans': '电话号码',
      'zh_Hant': '電話號碼',
    },
    'fbi8ed9i': {
      'en': 'Language',
      'de': 'Sprache',
      'es': 'Idioma',
      'it': 'Lingua',
      'ja': '言語',
      'ko': '언어',
      'pt': 'Linguagem',
      'ru': 'Язык',
      'zh_Hans': '语言',
      'zh_Hant': '語言',
    },
    'pkdez3pf': {
      'en': 'Notification Settings',
      'de': 'Benachrichtigungseinstellungen',
      'es': 'Configuración de las notificaciones',
      'it': 'Impostazioni di notifica',
      'ja': '通知設定',
      'ko': '알림 설정',
      'pt': 'Configurações de notificação',
      'ru': 'Настройки уведомлений',
      'zh_Hans': '通知设置',
      'zh_Hant': '通知設置',
    },
    'g28vd6z2': {
      'en': 'Log out of account',
      'de': 'Melden Sie sich vom Konto ab',
      'es': 'Cerrar sesión en la cuenta',
      'it': 'Esci dall\'account',
      'ja': 'アカウントからログアウトする',
      'ko': '계정에서 로그아웃',
      'pt': 'Sair da conta',
      'ru': 'Выйти из аккаунта',
      'zh_Hans': '退出帐户',
      'zh_Hant': '退出帳戶',
    },
    'xd6urxaa': {
      'en': 'Log Out?',
      'de': 'Ausloggen?',
      'es': '¿Cerrar sesión?',
      'it': 'Disconnettersi?',
      'ja': 'ログアウト？',
      'ko': '로그 아웃?',
      'pt': 'Sair?',
      'ru': 'Выйти?',
      'zh_Hans': '登出？',
      'zh_Hant': '登出？',
    },
    'ey55qnk7': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // ResetPasswordPage
  {
    'cqxtbc32': {
      'en': 'Reset Password',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'it': 'Resetta la password',
      'ja': 'パスワードを再設定する',
      'ko': '암호를 재설정',
      'pt': 'Redefinir senha',
      'ru': 'Сброс пароля',
      'zh_Hans': '重设密码',
      'zh_Hant': '重設密碼',
    },
    '6niwioeg': {
      'en': 'Email Address',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'zh_Hans': '电子邮件地址',
      'zh_Hant': '電子郵件地址',
    },
    '77bf2fti': {
      'en': 'Enter your email...',
      'de': 'Geben sie ihre E-Mail Adresse ein...',
      'es': 'Introduce tu correo electrónico...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ja': 'メールアドレスを入力...',
      'ko': '이메일을 입력하세요...',
      'pt': 'Digite seu e-mail...',
      'ru': 'Введите адрес электронной почты...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵箱...',
    },
    'hy2poh8j': {
      'en': 'Send email',
      'de': 'E-Mail senden',
      'es': 'Enviar correo electrónico',
      'it': 'Invia una email',
      'ja': 'メールを送る',
      'ko': '이메일을 보내',
      'pt': 'Enviar email',
      'ru': 'Отправить письмо',
      'zh_Hans': '发电子邮件',
      'zh_Hant': '發電子郵件',
    },
  },
  // NiggaView
  {
    'zorf0g0k': {
      'en': 'Search listings...',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'c7efh7h9': {
      'en': 'Homes',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ezmwapjx': {
      'en': 'Maidstone, San Antonio, Tx.',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'txfzukj0': {
      'en': '\$210/night',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wzbnmpy2': {
      'en': '32 miles away',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wzdpm4mj': {
      'en': '4.25',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'vzaq8vms': {
      'en': 'Maidstone, San Antonio, Tx.',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'r9o5w0d5': {
      'en': '\$210/night',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'e68qpqk6': {
      'en': '32 miles away',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ze2slqls': {
      'en': '4.25',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nbh0ng82': {
      'en': 'Beachfront',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ous2w87n': {
      'en': 'Maidstone, San Antonio, Tx.',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jirgowpb': {
      'en': '\$210/night',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '91ghn00e': {
      'en': '32 miles away',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'svb6natr': {
      'en': '4.25',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'mkssjpc4': {
      'en': 'Maidstone, San Antonio, Tx.',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ne4su3xp': {
      'en': '\$210/night',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'msvz7m86': {
      'en': '32 miles away',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rgzhelbm': {
      'en': '4.25',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6owmq9ma': {
      'en': 'Nature',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0ntsdg06': {
      'en': 'Maidstone, San Antonio, Tx.',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '29h6vsgp': {
      'en': '\$210/night',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5opj5892': {
      'en': '32 miles away',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'clrs0yg9': {
      'en': '4.25',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xjr155q8': {
      'en': 'Maidstone, San Antonio, Tx.',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qeuo4lfz': {
      'en': '\$210/night',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ujvami4s': {
      'en': '32 miles away',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jgte0t5a': {
      'en': '4.25',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lwqtiosz': {
      'en': 'Home',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // UserHeader
  {
    '0kaz33e2': {
      'en': 'Welcome',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Miscellaneous
  {
    'knqm8pqr': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f5hj143q': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f5izo0ud': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tcy3n4gt': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qy733tx4': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qub432x1': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uax3ryw3': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1qpwkwtd': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'h9utn8nz': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lxn7foe9': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bb19jivx': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'epcm5t8g': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gi4phigu': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fih28u85': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w6ura96x': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0u4rzz21': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v9zhsmoc': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2d971vsx': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '39rderir': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm39mpals': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ijkn44bn': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'alest3a2': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dshj78r6': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'puv2hb4o': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bupwemdf': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
