import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'pt', 'es', 'it', 'de', 'zh_Hans', 'zh_Hant', 'ru', 'ja', 'ko'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? ptText = '',
    String? esText = '',
    String? itText = '',
    String? deText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? ruText = '',
    String? jaText = '',
    String? koText = '',
  }) =>
      [
        enText,
        ptText,
        esText,
        itText,
        deText,
        zh_HansText,
        zh_HantText,
        ruText,
        jaText,
        koText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // TouristAttractionsPage
  {
    'xo0q40bn': {
      'en': 'Search tourist points...',
      'de': 'Touristische Punkte suchen...',
      'es': 'Buscar puntos turísticos...',
      'it': 'Cerca punti turistici...',
      'ja': '観光ポイントを検索...',
      'ko': '관광지 검색...',
      'pt': 'Pesquisar pontos turísticos...',
      'ru': 'Поиск туристических точек...',
      'zh_Hans': '搜索旅游点...',
      'zh_Hant': '搜索旅遊點...',
    },
    'gicrqril': {
      'en': 'Tourist Points',
      'de': 'Touristenpunkte',
      'es': 'Puntos Turísticos',
      'it': 'Punti turistici',
      'ja': '観光ポイント',
      'ko': '관광 포인트',
      'pt': 'Pontos Turísticos',
      'ru': 'Туристические точки',
      'zh_Hans': '旅游点',
      'zh_Hant': '旅遊點',
    },
    'n1canlv2': {
      'en': 'No tourist attractions found.',
      'de': 'Keine Touristenattraktionen gefunden.',
      'es': 'No se encontraron atracciones turísticas.',
      'it': 'Nessuna attrazione turistica trovata.',
      'ja': '観光スポットは見つかりませんでした。',
      'ko': '검색된 관광명소가 없습니다.',
      'pt': 'Nenhuma atração turística encontrada.',
      'ru': 'Туристических достопримечательностей не найдено.',
      'zh_Hans': '没有找到旅游景点。',
      'zh_Hant': '沒有找到旅遊景點。',
    },
    '7b1e17ez': {
      'en': 'No tourist attractions match your search criteria.',
      'de': 'Keine Touristenattraktionen entsprechen Ihren Suchkriterien.',
      'es':
          'Ninguna atracción turística coincide con sus criterios de búsqueda.',
      'it':
          'Nessuna attrazione turistica corrisponde ai tuoi criteri di ricerca.',
      'ja': '検索条件に一致する観光スポットはありません。',
      'ko': '검색 조건과 일치하는 관광지가 없습니다.',
      'pt':
          'Nenhuma atração turística corresponde aos seus critérios de pesquisa.',
      'ru':
          'Ни одна туристическая достопримечательность не соответствует вашим критериям поиска.',
      'zh_Hans': '没有符合您搜索条件的旅游景点。',
      'zh_Hant': '沒有符合您搜索條件的旅遊景點。',
    },
  },
  // AuthPage
  {
    'wmm1js2a': {
      'en': 'Sign In',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'it': 'Registrazione',
      'ja': 'サインイン',
      'ko': '로그인',
      'pt': 'Entrar',
      'ru': 'Войти',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    '320mgrwf': {
      'en': 'Email Address',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'zh_Hans': '电子邮件地址',
      'zh_Hant': '電子郵件地址',
    },
    'jdrn7y5r': {
      'en': 'Enter your email...',
      'de': 'Geben sie ihre E-Mail Adresse ein...',
      'es': 'Introduce tu correo electrónico...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ja': 'メールアドレスを入力...',
      'ko': '이메일을 입력하세요...',
      'pt': 'Digite seu e-mail...',
      'ru': 'Введите адрес электронной почты...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵箱...',
    },
    '0rzuy9rl': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'pt': 'Senha',
      'ru': 'Пароль',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'h3mmrgp9': {
      'en': 'Enter your password...',
      'de': 'Geben Sie Ihr Passwort ein...',
      'es': 'Ingresa tu contraseña...',
      'it': 'Inserisci la tua password...',
      'ja': 'パスワードを入力してください...',
      'ko': '비밀번호를 입력하세요...',
      'pt': 'Coloque sua senha...',
      'ru': 'Введите ваш пароль...',
      'zh_Hans': '输入您的密码...',
      'zh_Hant': '輸入您的密碼...',
    },
    'm3sx80ro': {
      'en': 'Sign In',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'it': 'Registrazione',
      'ja': 'サインイン',
      'ko': '로그인',
      'pt': 'Entrar',
      'ru': 'Войти',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    '2t4avplr': {
      'en': 'Forgot Password?',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'it': 'Ha dimenticato la password?',
      'ja': 'パスワードをお忘れですか？',
      'ko': '비밀번호를 잊으 셨나요?',
      'pt': 'Esqueceu sua senha?',
      'ru': 'Забыли пароль?',
      'zh_Hans': '忘记密码？',
      'zh_Hant': '忘記密碼？',
    },
    'akh4dv0l': {
      'en': 'Or use a social account to login',
      'de': 'Oder verwenden Sie ein soziales Konto, um sich anzumelden',
      'es': 'O use una cuenta social para iniciar sesión',
      'it': 'Oppure utilizza un account social per accedere',
      'ja': 'またはソーシャルアカウントを使用してログインしてください',
      'ko': '또는 소셜 계정을 사용하여 로그인하세요.',
      'pt': 'Ou use uma conta social para fazer login',
      'ru': 'Или используйте учетную запись социальной сети для входа',
      'zh_Hans': '或使用社交账号登录',
      'zh_Hant': '或使用社交賬號登錄',
    },
    'wmh90oaq': {
      'en': 'Sign Up',
      'de': 'Melden Sie sich an',
      'es': 'Inscribirse',
      'it': 'Iscrizione',
      'ja': 'サインアップ',
      'ko': '가입하기',
      'pt': 'Inscrever-se',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '报名',
      'zh_Hant': '報名',
    },
    '22v9866n': {
      'en': 'Upload your image',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    's34fmkz8': {
      'en': 'Username',
      'de': 'Nutzername',
      'es': 'Nombre de usuario',
      'it': 'Nome utente',
      'ja': 'ユーザー名',
      'ko': '사용자 이름',
      'pt': 'Nome de usuário',
      'ru': 'Имя пользователя',
      'zh_Hans': '用户名',
      'zh_Hant': '用戶名',
    },
    'cmc7lupt': {
      'en': 'Enter your username...',
      'de': 'Geben Sie Ihren Benutzernamen ein...',
      'es': 'Ingrese su nombre de usuario...',
      'it': 'Inserisci il tuo nome utente...',
      'ja': 'ユーザー名を入力して下さい...',
      'ko': '사용자 이름을 입력하세요...',
      'pt': 'Entre com seu nome de usuário...',
      'ru': 'Введите имя пользователя...',
      'zh_Hans': '输入你的用户名...',
      'zh_Hant': '輸入你的用戶名...',
    },
    '0eib5yeu': {
      'en': 'Email Address',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'zh_Hans': '电子邮件地址',
      'zh_Hant': '電子郵件地址',
    },
    'xn7gsla5': {
      'en': 'Enter your email...',
      'de': 'Geben sie ihre E-Mail Adresse ein...',
      'es': 'Introduce tu correo electrónico...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ja': 'メールアドレスを入力...',
      'ko': '이메일을 입력하세요...',
      'pt': 'Digite seu e-mail...',
      'ru': 'Введите адрес электронной почты...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵箱...',
    },
    '9m1ke9bp': {
      'en': 'Phone Number (Optional)',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'zh_Hans': '电子邮件地址',
      'zh_Hant': '電子郵件地址',
    },
    '3aye8874': {
      'en': 'Enter your phone number...',
      'de': 'Geben sie ihre E-Mail Adresse ein...',
      'es': 'Introduce tu correo electrónico...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ja': 'メールアドレスを入力...',
      'ko': '이메일을 입력하세요...',
      'pt': 'Digite seu e-mail...',
      'ru': 'Введите адрес электронной почты...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵箱...',
    },
    'pql4dbwn': {
      'en': 'Password',
      'de': 'Passwort',
      'es': 'Contraseña',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'pt': 'Senha',
      'ru': 'Пароль',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    '42pyp3xa': {
      'en': 'Enter your password...',
      'de': 'Geben Sie Ihr Passwort ein...',
      'es': 'Ingresa tu contraseña...',
      'it': 'Inserisci la tua password...',
      'ja': 'パスワードを入力してください...',
      'ko': '비밀번호를 입력하세요...',
      'pt': 'Coloque sua senha...',
      'ru': 'Введите ваш пароль...',
      'zh_Hans': '输入您的密码...',
      'zh_Hant': '輸入您的密碼...',
    },
    'f1abiaa0': {
      'en': 'Confirm Password',
      'de': 'Bestätige das Passwort',
      'es': 'confirmar Contraseña',
      'it': 'Conferma password',
      'ja': 'パスワードを認証する',
      'ko': '비밀번호 확인',
      'pt': 'Confirme sua senha',
      'ru': 'Подтвердите пароль',
      'zh_Hans': '确认密码',
      'zh_Hant': '確認密碼',
    },
    '60zputvu': {
      'en': 'Confirm your password...',
      'de': 'Bestätigen Sie Ihr Passwort...',
      'es': 'Confirmar la contraseña...',
      'it': 'Conferma la tua password...',
      'ja': 'あなたのパスワードを確認...',
      'ko': '암호를 확인...',
      'pt': 'Confirme sua senha...',
      'ru': 'Подтвердите ваш пароль...',
      'zh_Hans': '确认你的密码...',
      'zh_Hant': '確認你的密碼...',
    },
    'qzrvt30z': {
      'en': 'Create Account',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ko': '계정 만들기',
      'pt': 'Criar uma conta',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '创建账户',
      'zh_Hant': '創建賬戶',
    },
    '9yece9ll': {
      'en': 'Username is required',
      'de': 'Benutzername wird benötigt',
      'es': 'Se requiere nombre de usuario',
      'it': 'è richiesto il nome utente',
      'ja': 'ユーザー名は必須です',
      'ko': '사용자 이름이 필요합니다',
      'pt': 'Nome de usuário é requerido',
      'ru': 'Имя пользователя требуется',
      'zh_Hans': '用户名是必需的',
      'zh_Hant': '用戶名是必需的',
    },
    '5p48ncky': {
      'en': 'Username is too short',
      'de': 'Der Benutzername ist zu kurz',
      'es': 'El nombre de usuario es demasiado corto',
      'it': 'Il nome utente è troppo corto',
      'ja': 'ユーザー名が短すぎます',
      'ko': '사용자 이름이 너무 짧습니다.',
      'pt': 'O nome de usuário é muito curto',
      'ru': 'Имя пользователя слишком короткое',
      'zh_Hans': '用户名太短',
      'zh_Hant': '用戶名太短',
    },
    'xa1046c8': {
      'en': 'Username is too large',
      'de': 'Der Benutzername ist zu groß',
      'es': 'El nombre de usuario es demasiado grande',
      'it': 'Il nome utente è troppo grande',
      'ja': 'ユーザー名が大きすぎます',
      'ko': '사용자 이름이 너무 큽니다.',
      'pt': 'O nome de usuário é muito grande',
      'ru': 'Имя пользователя слишком велико',
      'zh_Hans': '用户名太大',
      'zh_Hant': '用戶名太大',
    },
    '2nffw11f': {
      'en': 'Username is invalid',
      'de': 'Benutzername ist ungültig',
      'es': 'Nombre de usuario invalido',
      'it': 'l\'username non è valido',
      'ja': 'ユーザー名が無効です',
      'ko': '사용자 이름이 잘못되었습니다',
      'pt': 'nome de usuário Inválido',
      'ru': 'Имя пользователя недействительно',
      'zh_Hans': '无效的用户名',
      'zh_Hant': '無效的用戶名',
    },
    '5opf8n6x': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'es': 'Por favor elija una opción del menú desplegable',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ko': '드롭다운에서 옵션을 선택하세요.',
      'pt': 'Escolha uma opção no menu suspenso',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'zh_Hans': '请从下拉列表中选择一个选项',
      'zh_Hant': '請從下拉列表中選擇一個選項',
    },
    'g3p5ser0': {
      'en': 'Email is required',
      'de': 'E-Mail ist erforderlich',
      'es': 'correo electronico es requerido',
      'it': 'L\'e-mail è obbligatoria',
      'ja': 'メールアドレスは必須です',
      'ko': '이메일은 필수입니다',
      'pt': 'O e-mail é obrigatório',
      'ru': 'Требуется электронная почта',
      'zh_Hans': '电子邮件为必填项',
      'zh_Hant': '電子郵件為必填項',
    },
    'iy88h2pz': {
      'en': 'Email is too short',
      'de': 'E-Mail ist zu kurz',
      'es': 'El correo electrónico es demasiado corto.',
      'it': 'L\'e-mail è troppo breve',
      'ja': 'メールが短すぎます',
      'ko': '이메일이 너무 짧습니다.',
      'pt': 'O e-mail é muito curto',
      'ru': 'Электронная почта слишком короткая',
      'zh_Hans': '电子邮件太短',
      'zh_Hant': '電子郵件太短',
    },
    'l4o3hjgr': {
      'en': 'Email is too long',
      'de': 'E-Mail ist zu lang',
      'es': 'El correo electrónico es demasiado largo.',
      'it': 'L\'e-mail è troppo lunga',
      'ja': 'メールが長すぎます',
      'ko': '이메일이 너무 깁니다.',
      'pt': 'O e-mail é muito longo',
      'ru': 'Электронная почта слишком длинная',
      'zh_Hans': '电子邮件太长',
      'zh_Hant': '電子郵件太長',
    },
    '6fhxfd03': {
      'en': 'Email is invalid',
      'de': 'E-Mail ist ungültig',
      'es': 'el correo electrónico es invalido',
      'it': 'L\'email non è valida',
      'ja': 'メールが無効です',
      'ko': '이메일이 잘못되었습니다',
      'pt': 'Email inválido',
      'ru': 'Электронная почта недействительна',
      'zh_Hans': '电子邮件无效',
      'zh_Hant': '電子郵件無效',
    },
    'n81nnjwg': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'es': 'Por favor elija una opción del menú desplegable',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ko': '드롭다운에서 옵션을 선택하세요.',
      'pt': 'Escolha uma opção no menu suspenso',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'zh_Hans': '请从下拉列表中选择一个选项',
      'zh_Hant': '請從下拉列表中選擇一個選項',
    },
    'xe78y1hq': {
      'en': 'Field is required',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cz4vojov': {
      'en': 'Please choose an option from the dropdown',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0msnc8mm': {
      'en': 'Password is required',
      'de': 'Passwort wird benötigt',
      'es': 'se requiere contraseña',
      'it': 'E \'richiesta la password',
      'ja': 'パスワードが必要',
      'ko': '비밀번호가 필요합니다',
      'pt': 'Senha requerida',
      'ru': 'Необходим пароль',
      'zh_Hans': '密码是必需的',
      'zh_Hant': '密碼是必需的',
    },
    'wuzfk8gw': {
      'en': 'Password is too short',
      'de': 'Das Passwort ist zu kurz',
      'es': 'La contraseña es demasiado corta',
      'it': 'La password è troppo corta',
      'ja': 'パスワードが短すぎます',
      'ko': '비밀번호가 너무 짧습니다',
      'pt': 'A senha é muito curta',
      'ru': 'Пароль слишком короткий',
      'zh_Hans': '密码太短',
      'zh_Hant': '密碼太短',
    },
    'l8q2cylv': {
      'en': 'Password is too long',
      'de': 'Das Passwort ist zu lang',
      'es': 'La contraseña es demasiado larga',
      'it': 'La password è troppo lunga',
      'ja': 'パスワードが長すぎます',
      'ko': '비밀번호가 너무 깁니다.',
      'pt': 'A senha é muito longa',
      'ru': 'Пароль слишком длинный',
      'zh_Hans': '密码太长',
      'zh_Hant': '密碼太長',
    },
    '0htf1ui2': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'es': 'Por favor elija una opción del menú desplegable',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ko': '드롭다운에서 옵션을 선택하세요.',
      'pt': 'Escolha uma opção no menu suspenso',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'zh_Hans': '请从下拉列表中选择一个选项',
      'zh_Hant': '請從下拉列表中選擇一個選項',
    },
    '19jdhf1m': {
      'en': 'Confirm Password is required',
      'de': 'Bestätigen Sie, dass ein Passwort erforderlich ist',
      'es': 'Confirmar Se requiere contraseña',
      'it': 'È richiesta la conferma della password',
      'ja': 'パスワードが必要であることを確認してください',
      'ko': '비밀번호 확인이 필요합니다',
      'pt': 'Confirmar senha é obrigatório',
      'ru': 'Требуется подтверждение пароля',
      'zh_Hans': '需要确认密码',
      'zh_Hant': '需要確認密碼',
    },
    'iuzgg16i': {
      'en': 'Password is too short',
      'de': 'Das Passwort ist zu kurz',
      'es': 'La contraseña es demasiado corta',
      'it': 'La password è troppo corta',
      'ja': 'パスワードが短すぎます',
      'ko': '비밀번호가 너무 짧습니다',
      'pt': 'A senha é muito curta',
      'ru': 'Пароль слишком короткий',
      'zh_Hans': '密码太短',
      'zh_Hant': '密碼太短',
    },
    'w6dwu2ir': {
      'en': 'Password is too long',
      'de': 'Das Passwort ist zu lang',
      'es': 'La contraseña es demasiado larga',
      'it': 'La password è troppo lunga',
      'ja': 'パスワードが長すぎます',
      'ko': '비밀번호가 너무 깁니다.',
      'pt': 'A senha é muito longa',
      'ru': 'Пароль слишком длинный',
      'zh_Hans': '密码太长',
      'zh_Hant': '密碼太長',
    },
    'hec0ujos': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'es': 'Por favor elija una opción del menú desplegable',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ko': '드롭다운에서 옵션을 선택하세요.',
      'pt': 'Escolha uma opção no menu suspenso',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'zh_Hans': '请从下拉列表中选择一个选项',
      'zh_Hant': '請從下拉列表中選擇一個選項',
    },
    '4vjon5z7': {
      'en': 'Sign up using a social account',
      'de': 'Melden Sie sich mit einem sozialen Konto an',
      'es': 'Regístrese usando una cuenta social',
      'it': 'Iscriviti utilizzando un account social',
      'ja': 'ソーシャルアカウントを使用してサインアップする',
      'ko': '소셜 계정을 사용하여 가입',
      'pt': 'Inscreva-se usando uma conta social',
      'ru': 'Зарегистрируйтесь с помощью социальной учетной записи',
      'zh_Hans': '使用社交帐户注册',
      'zh_Hant': '使用社交帳戶註冊',
    },
    's5r88r9j': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // ProfilePage
  {
    'qawb6l2w': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'it': 'Impostazioni',
      'ja': '設定',
      'ko': '설정',
      'pt': 'Configurações',
      'ru': 'Настройки',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
    'ehnyf6k8': {
      'en': 'Phone Number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'it': 'Numero di telefono',
      'ja': '電話番号',
      'ko': '전화 번호',
      'pt': 'Número de telefone',
      'ru': 'Номер телефона',
      'zh_Hans': '电话号码',
      'zh_Hant': '電話號碼',
    },
    'fbi8ed9i': {
      'en': 'Language',
      'de': 'Sprache',
      'es': 'Idioma',
      'it': 'Lingua',
      'ja': '言語',
      'ko': '언어',
      'pt': 'Linguagem',
      'ru': 'Язык',
      'zh_Hans': '语言',
      'zh_Hant': '語言',
    },
    'pkdez3pf': {
      'en': 'Notification Settings',
      'de': 'Benachrichtigungseinstellungen',
      'es': 'Configuración de las notificaciones',
      'it': 'Impostazioni di notifica',
      'ja': '通知設定',
      'ko': '알림 설정',
      'pt': 'Configurações de notificação',
      'ru': 'Настройки уведомлений',
      'zh_Hans': '通知设置',
      'zh_Hant': '通知設置',
    },
    'g28vd6z2': {
      'en': 'Log out of account',
      'de': 'Melden Sie sich vom Konto ab',
      'es': 'Cerrar sesión en la cuenta',
      'it': 'Esci dall\'account',
      'ja': 'アカウントからログアウトする',
      'ko': '계정에서 로그아웃',
      'pt': 'Sair da conta',
      'ru': 'Выйти из аккаунта',
      'zh_Hans': '退出帐户',
      'zh_Hant': '退出帳戶',
    },
    'xd6urxaa': {
      'en': 'Log Out?',
      'de': 'Ausloggen?',
      'es': '¿Cerrar sesión?',
      'it': 'Disconnettersi?',
      'ja': 'ログアウト？',
      'ko': '로그 아웃?',
      'pt': 'Sair?',
      'ru': 'Выйти?',
      'zh_Hans': '登出？',
      'zh_Hant': '登出？',
    },
    'ey55qnk7': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // TouristAttractionDetailsPage
  {
    'djcfwre5': {
      'en': 'Se on map',
      'de': 'Siehe auf der Karte',
      'es': 'Ver en el mapa',
      'it': 'Vedi sulla mappa',
      'ja': '地図上の瀬',
      'ko': '지도상의 Se',
      'pt': 'Veja no mapa',
      'ru': 'Се на карте',
      'zh_Hans': '地图上的 Se',
      'zh_Hant': '地圖上的 Se',
    },
    '7ylls5nq': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // NotificationSettingsPage
  {
    'nfusw00s': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'es': 'Ajustes',
      'it': 'Impostazioni',
      'ja': '設定',
      'ko': '설정',
      'pt': 'Configurações',
      'ru': 'Настройки',
      'zh_Hans': '设置',
      'zh_Hant': '設置',
    },
    'hun8i9v4': {
      'en':
          'Choose what notifcations you want to recieve below and we will update the settings.',
      'de':
          'Wählen Sie unten aus, welche Benachrichtigungen Sie erhalten möchten, und wir aktualisieren die Einstellungen.',
      'es':
          'Elija qué notificaciones desea recibir a continuación y actualizaremos la configuración.',
      'it':
          'Scegli qui sotto quali notifiche desideri ricevere e aggiorneremo le impostazioni.',
      'ja': '受け取りたい通知を以下から選択してください。設定が更新されます。',
      'ko': '아래에서 받고 싶은 알림을 선택하면 설정이 업데이트됩니다.',
      'pt':
          'Escolha abaixo quais notificações você deseja receber e atualizaremos as configurações.',
      'ru':
          'Ниже выберите, какие уведомления вы хотите получать, и мы обновим настройки.',
      'zh_Hans': '在下面选择您想要接收的通知，我们将更新设置。',
      'zh_Hant': '在下面選擇您想要接收的通知，我們將更新設置。',
    },
    '6ctnjjo7': {
      'en': 'Push Notifications',
      'de': 'Mitteilungen',
      'es': 'Notificaciones push',
      'it': 'Le notifiche push',
      'ja': 'プッシュ通知',
      'ko': '푸시 알림',
      'pt': 'Notificações via push',
      'ru': 'Всплывающее уведомление',
      'zh_Hans': '推送通知',
      'zh_Hant': '推送通知',
    },
    '79ftyz56': {
      'en':
          'Receive Push notifications from our application on a semi regular basis.',
      'de':
          'Erhalten Sie regelmäßig Push-Benachrichtigungen von unserer Anwendung.',
      'es':
          'Reciba notificaciones push de nuestra aplicación de forma semiregular.',
      'it':
          'Ricevi notifiche push dalla nostra applicazione su base semi-regolare.',
      'ja': 'アプリケーションからプッシュ通知を半定期的に受信します。',
      'ko': '우리 애플리케이션으로부터 정기적으로 푸시 알림을 받습니다.',
      'pt': 'Receba notificações push de nosso aplicativo regularmente.',
      'ru':
          'Получайте push-уведомления из нашего приложения на полурегулярной основе.',
      'zh_Hans': '定期从我们的应用程序接收推送通知。',
      'zh_Hant': '定期從我們的應用程序接收推送通知。',
    },
    'yexwq7ef': {
      'en': 'Email Notifications',
      'de': 'E-Mail Benachrichtigungen',
      'es': 'Notificaciónes de Correo Electrónico',
      'it': 'notifiche di posta elettronica',
      'ja': '電子メール通知',
      'ko': '이메일 알림',
      'pt': 'Notificações por e-mail',
      'ru': 'Уведомления по электронной почте',
      'zh_Hans': '电子邮件通知',
      'zh_Hant': '電子郵件通知',
    },
    's1ifynxu': {
      'en':
          'Receive email notifications from our marketing team about new features.',
      'de':
          'Erhalten Sie E-Mail-Benachrichtigungen von unserem Marketingteam über neue Funktionen.',
      'es':
          'Reciba notificaciones por correo electrónico de nuestro equipo de marketing sobre nuevas funciones.',
      'it':
          'Ricevi notifiche via email dal nostro team di marketing sulle nuove funzionalità.',
      'ja': '新機能に関するマーケティング チームからの電子メール通知を受け取ります。',
      'ko': '마케팅팀으로부터 새로운 기능에 대한 이메일 알림을 받으세요.',
      'pt':
          'Receba notificações por e-mail de nossa equipe de marketing sobre novos recursos.',
      'ru':
          'Получайте уведомления по электронной почте от нашей маркетинговой команды о новых функциях.',
      'zh_Hans': '接收来自我们营销团队的有关新功能的电子邮件通知。',
      'zh_Hant': '接收來自我們營銷團隊的有關新功能的電子郵件通知。',
    },
    '2l2ytrbm': {
      'en': 'Location Services',
      'de': 'Standortdienste',
      'es': 'Servicios de localización',
      'it': 'Servizi di localizzazione',
      'ja': '位置情報サービス',
      'ko': '위치 서비스',
      'pt': 'Serviços de localização',
      'ru': 'Сервисы определения местоположения',
      'zh_Hans': '位置服务',
      'zh_Hant': '位置服務',
    },
    'j7ny9rep': {
      'en':
          'Allow us to track your location, this helps keep track of spending and keeps you safe.',
      'de':
          'Erlauben Sie uns, Ihren Standort zu verfolgen. Dies hilft Ihnen, den Überblick über Ihre Ausgaben zu behalten und schützt Sie.',
      'es':
          'Permítanos rastrear su ubicación, esto ayuda a realizar un seguimiento de sus gastos y lo mantiene seguro.',
      'it':
          'Consentici di tracciare la tua posizione, questo aiuta a tenere traccia delle spese e ti mantiene al sicuro.',
      'ja': 'あなたの位置を追跡できるようにしてください。これは支出を追跡し、あなたの安全を守るのに役立ちます。',
      'ko': '귀하의 위치를 ​​추적하도록 허용하면 지출을 추적하고 귀하를 안전하게 보호하는 데 도움이 됩니다.',
      'pt':
          'Permita-nos rastrear sua localização, isso ajuda a controlar os gastos e mantém você seguro.',
      'ru':
          'Позвольте нам отслеживать ваше местоположение, это поможет отслеживать расходы и обеспечит вашу безопасность.',
      'zh_Hans': '允许我们跟踪您的位置，这有助于跟踪支出并确保您的安全。',
      'zh_Hant': '允許我們跟踪您的位置，這有助於跟踪支出並確保您的安全。',
    },
    '7myzi1ln': {
      'en': 'Save Changes',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'it': 'Salvare le modifiche',
      'ja': '変更内容を保存',
      'ko': '변경 사항을 저장하다',
      'pt': 'Salvar alterações',
      'ru': 'Сохранить изменения',
      'zh_Hans': '保存更改',
      'zh_Hant': '保存更改',
    },
    'nr80q47a': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // LanguageSettingsPage
  {
    'x4abnblb': {
      'en': 'Languages',
      'de': 'Sprachen',
      'es': 'Idiomas',
      'it': 'Le lingue',
      'ja': '言語',
      'ko': '언어',
      'pt': 'línguas',
      'ru': 'Языки',
      'zh_Hans': '语言',
      'zh_Hant': '語言',
    },
    'ibzpf1do': {
      'en': 'Select the language you want to set.',
      'de': 'Wählen Sie die Sprache aus, die Sie einstellen möchten.',
      'es': 'Seleccione el idioma que desea configurar.',
      'it': 'Seleziona la lingua che desideri impostare.',
      'ja': '設定したい言語を選択します。',
      'ko': '설정하려는 언어를 선택하세요.',
      'pt': 'Selecione o idioma que deseja definir.',
      'ru': 'Выберите язык, который вы хотите установить.',
      'zh_Hans': '选择您要设置的语言。',
      'zh_Hant': '選擇您要設置的語言。',
    },
    'q2mge58a': {
      'en': 'Save Changes',
      'de': 'Änderungen speichern',
      'es': 'Guardar cambios',
      'it': 'Salvare le modifiche',
      'ja': '変更内容を保存',
      'ko': '변경 사항을 저장하다',
      'pt': 'Salvar alterações',
      'ru': 'Сохранить изменения',
      'zh_Hans': '保存更改',
      'zh_Hant': '保存更改',
    },
    'adk74c1e': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // ResetPasswordPage
  {
    '7yfeh8ip': {
      'en': 'Reset Password',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'it': 'Resetta la password',
      'ja': 'パスワードを再設定する',
      'ko': '암호를 재설정',
      'pt': 'Redefinir senha',
      'ru': 'Сброс пароля',
      'zh_Hans': '重设密码',
      'zh_Hant': '重設密碼',
    },
    'li625sqi': {
      'en':
          'Enter your email and we’ll send you a link to get back into your account.',
      'de':
          'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link, um wieder auf Ihr Konto zuzugreifen.',
      'es':
          'Ingrese su correo electrónico y le enviaremos un enlace para regresar a su cuenta.',
      'it':
          'Inserisci la tua email e ti invieremo un collegamento per rientrare nel tuo account.',
      'ja': 'メールアドレスを入力すると、アカウントに戻るためのリンクが送信されます。',
      'ko': '이메일을 입력하시면 계정에 다시 로그인할 수 있는 링크를 보내드립니다.',
      'pt':
          'Digite seu e-mail e enviaremos um link para você voltar à sua conta.',
      'ru':
          'Введите свой адрес электронной почты, и мы вышлем вам ссылку для возврата в вашу учетную запись.',
      'zh_Hans': '输入您的电子邮件，我们将向您发送一个链接以返回您的帐户。',
      'zh_Hant': '輸入您的電子郵件，我們將向您發送一個鏈接以返回您的帳戶。',
    },
    'hdgvm0jt': {
      'en': 'Email Address',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'zh_Hans': '电子邮件地址',
      'zh_Hant': '電子郵件地址',
    },
    'gou294pm': {
      'en': 'Enter your email...',
      'de': 'Geben sie ihre E-Mail Adresse ein...',
      'es': 'Introduce tu correo electrónico...',
      'it': 'Inserisci il tuo indirizzo email...',
      'ja': 'メールアドレスを入力...',
      'ko': '이메일을 입력하세요...',
      'pt': 'Digite seu e-mail...',
      'ru': 'Введите адрес электронной почты...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵箱...',
    },
    '2nhfom2x': {
      'en': 'Reset Password',
      'de': 'Passwort zurücksetzen',
      'es': 'Restablecer la contraseña',
      'it': 'Resetta la password',
      'ja': 'パスワードを再設定する',
      'ko': '암호를 재설정',
      'pt': 'Redefinir senha',
      'ru': 'Сброс пароля',
      'zh_Hans': '重设密码',
      'zh_Hant': '重設密碼',
    },
    '1ywxv7q5': {
      'en': 'Email required',
      'de': 'Email (erforderlich',
      'es': 'Correo electronico (requerido',
      'it': 'Email (obbligatorio',
      'ja': 'メールアドレスが必要です',
      'ko': '이메일 필요',
      'pt': 'Email (obrigatório',
      'ru': 'Требуется электронная почта',
      'zh_Hans': '需要电子邮件',
      'zh_Hant': '需要電子郵件',
    },
    'whvtlc3h': {
      'en': 'Invalid Email',
      'de': 'Ungültige E-Mail',
      'es': 'Email inválido',
      'it': 'E-mail non valido',
      'ja': '無効な電子メール',
      'ko': '잘못된 이메일',
      'pt': 'E-mail inválido',
      'ru': 'Неверный адрес электронной почты',
      'zh_Hans': '不合规电邮',
      'zh_Hant': '不合規電郵',
    },
    '54pioh6f': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'es': 'Por favor elija una opción del menú desplegable',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ko': '드롭다운에서 옵션을 선택하세요.',
      'pt': 'Escolha uma opção no menu suspenso',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'zh_Hans': '请从下拉列表中选择一个选项',
      'zh_Hant': '請從下拉列表中選擇一個選項',
    },
    'dc7fkgvo': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // ChangePhoneSettingsPage
  {
    'h8alx3gy': {
      'en': 'Edit Phone Number',
      'de': 'Telefonnummer bearbeiten',
      'es': 'Editar número de teléfono',
      'it': 'Modifica numero di telefono',
      'ja': '電話番号を編集する',
      'ko': '전화번호 수정',
      'pt': 'Editar número de telefone',
      'ru': 'Изменить номер телефона',
      'zh_Hans': '编辑电话号码',
      'zh_Hant': '編輯電話號碼',
    },
    'oirobqdc': {
      'en': 'You can edit your phone number below.',
      'de': 'Sie können Ihre Telefonnummer unten bearbeiten.',
      'es': 'Puede editar su número de teléfono a continuación.',
      'it': 'Puoi modificare il tuo numero di telefono qui sotto.',
      'ja': '以下で電話番号を編集できます。',
      'ko': '아래에서 전화번호를 편집할 수 있습니다.',
      'pt': 'Você pode editar seu número de telefone abaixo.',
      'ru': 'Вы можете отредактировать свой номер телефона ниже.',
      'zh_Hans': '您可以在下面编辑您的电话号码。',
      'zh_Hant': '您可以在下面編輯您的電話號碼。',
    },
    'hsqqhnff': {
      'en': 'Phone Number',
      'de': 'Telefonnummer',
      'es': 'Número de teléfono',
      'it': 'Numero di telefono',
      'ja': '電話番号',
      'ko': '전화 번호',
      'pt': 'Número de telefone',
      'ru': 'Номер телефона',
      'zh_Hans': '电话号码',
      'zh_Hant': '電話號碼',
    },
    'xs8zvdpd': {
      'en': 'Enter your phone number...',
      'de': 'Gib deine Telefonnummer ein...',
      'es': 'Ingrese su número telefónico...',
      'it': 'Inserisci il tuo numero di telefono...',
      'ja': '電話番号を入力してください...',
      'ko': '전화번호를 입력하세요...',
      'pt': 'Digite seu número de telefone...',
      'ru': 'Введите свой номер телефона...',
      'zh_Hans': '输入你的电话号码...',
      'zh_Hant': '輸入你的電話號碼...',
    },
    '728dyye6': {
      'en': 'Save Phone Number',
      'de': 'Telefonnummer speichern',
      'es': 'Guardar número de teléfono',
      'it': 'Salva numero di telefono',
      'ja': '電話番号を保存する',
      'ko': '전화번호 저장',
      'pt': 'Salvar número de telefone',
      'ru': 'Сохранить номер телефона',
      'zh_Hans': '保存电话号码',
      'zh_Hant': '保存電話號碼',
    },
    'powxbqnu': {
      'en': 'Email required',
      'de': 'Email (erforderlich',
      'es': 'Correo electronico (requerido',
      'it': 'Email (obbligatorio',
      'ja': 'メールアドレスが必要です',
      'ko': '이메일 필요',
      'pt': 'Email (obrigatório',
      'ru': 'Требуется электронная почта',
      'zh_Hans': '需要电子邮件',
      'zh_Hant': '需要電子郵件',
    },
    'icrilhmu': {
      'en': 'Invalid Email',
      'de': 'Ungültige E-Mail',
      'es': 'Email inválido',
      'it': 'E-mail non valido',
      'ja': '無効な電子メール',
      'ko': '잘못된 이메일',
      'pt': 'E-mail inválido',
      'ru': 'Неверный адрес электронной почты',
      'zh_Hans': '不合规电邮',
      'zh_Hant': '不合規電郵',
    },
    'aqkw6kfw': {
      'en': 'Please choose an option from the dropdown',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'es': 'Por favor elija una opción del menú desplegable',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ko': '드롭다운에서 옵션을 선택하세요.',
      'pt': 'Escolha uma opção no menu suspenso',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'zh_Hans': '请从下拉列表中选择一个选项',
      'zh_Hant': '請從下拉列表中選擇一個選項',
    },
    'syu106z4': {
      'en': 'Home',
      'de': 'Heim',
      'es': 'Hogar',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // UserHeader
  {
    '0kaz33e2': {
      'en': 'Welcome',
      'de': 'Willkommen',
      'es': 'Bienvenido',
      'it': 'Benvenuto',
      'ja': 'いらっしゃいませ',
      'ko': '환영',
      'pt': 'Bem-vindo',
      'ru': 'Добро пожаловать',
      'zh_Hans': '欢迎',
      'zh_Hant': '歡迎',
    },
  },
  // Miscellaneous
  {
    'knqm8pqr': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'f5hj143q': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wvl5iqct': {
      'en': 'Please, give us permission to send you notifications.',
      'de':
          'Bitte erteilen Sie uns die Erlaubnis, Ihnen Benachrichtigungen zu senden.',
      'es': 'Por favor, danos permiso para enviarte notificaciones.',
      'it': 'Per favore, dacci il permesso di inviarti notifiche.',
      'ja': '通知の送信を許可してください。',
      'ko': '귀하에게 알림을 보낼 수 있도록 허가해 주십시오.',
      'pt': 'Por favor, dê-nos permissão para lhe enviar notificações.',
      'ru': 'Пожалуйста, дайте нам разрешение на отправку вам уведомлений.',
      'zh_Hans': '请允许我们向您发送通知。',
      'zh_Hant': '請允許我們向您發送通知。',
    },
    'jmzbjshd': {
      'en': 'Please, give us permission to track your location.',
      'de':
          'Bitte erteilen Sie uns die Erlaubnis, Ihren Standort zu verfolgen.',
      'es': 'Por favor, danos permiso para rastrear tu ubicación.',
      'it': 'Per favore, dacci il permesso di tracciare la tua posizione.',
      'ja': 'あなたの位置を追跡することを許可してください。',
      'ko': '귀하의 위치를 ​​추적할 수 있는 권한을 부여해 주십시오.',
      'pt': 'Por favor, dê-nos permissão para rastrear sua localização.',
      'ru': 'Пожалуйста, дайте нам разрешение отслеживать ваше местоположение.',
      'zh_Hans': '请允许我们跟踪您的位置。',
      'zh_Hant': '請允許我們跟踪您的位置。',
    },
    'f5izo0ud': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tcy3n4gt': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qy733tx4': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'qub432x1': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'uax3ryw3': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1qpwkwtd': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'h9utn8nz': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lxn7foe9': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bb19jivx': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'epcm5t8g': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'gi4phigu': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fih28u85': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w6ura96x': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0u4rzz21': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'v9zhsmoc': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2d971vsx': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '39rderir': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'm39mpals': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ijkn44bn': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'alest3a2': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dshj78r6': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'puv2hb4o': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bupwemdf': {
      'en': '',
      'de': '',
      'es': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
